mise en place du routeur
WildCodeSchool/lyon-js-03-20-p2-g4 pull request #30
Opened 2020-04-15 13:40 UTC by Gottfrieden

US faite à 4.

2020-04-15 13:48 UTC, Rincevent42 approved these changes
Branche fonctionnelle.

2020-04-16 08:34 UTC, ComicScrip requested changes
Merci de merger dev sur cette branche

2020-04-16 08:34 UTC, ComicScrip commented on src/pages/Result.js
> +                <Link to="/">
Ok, j'imagine que les liens dupliqués de Result.js sont là juste pour tester la fonctionnalité

2020-04-16 08:57 UTC, AmelieChevalier commented on src/pages/Result.js
> +                <Link to="/">
Oui, c'est ça. On mergera dev dans us4 dès que l'us3 sera mergée.

2020-04-16 14:35 UTC, Gottfrieden commented
@ComicScrip  Merge dev into feature/us4. Ready to be merged in dev

2020-04-16 14:38 UTC, ComicScrip approved these changes

2020-04-16 14:39 UTC, merged