Feature/us7
WildCodeSchool/lyon-js-03-20-p2-g4 pull request #37
Opened 2020-04-22 09:00 UTC by Gottfrieden

J'ai travaillé dessus, tout est ok.

2020-04-23 14:03 UTC, Gottfrieden commented
@ComicScrip  On a géré les conflits, c'est tout bon pour déployer sur dev

2020-04-24 06:36 UTC, ComicScrip requested changes

2020-04-24 06:36 UTC, ComicScrip commented on src/components/FilmCard.js
> +    const posterPath3 = listAction.results[this.props.index + 2].poster_path;
Attention : quand on arrivera en bout de liste, listAction.results[this.props.index + 1] sera undefined

2020-04-24 06:36 UTC, ComicScrip commented on src/pages/MatchRoom.js
> +      this.setState({ user1List, index: (this.state.index + 1), finishedSession: true });
possibilité de simplifier le if/else :
`this.setState({ user1List, index: (this.state.index + 1), finishedSession: (this.state.index === this.state.list.length - 1) });`

2020-04-24 06:36 UTC, ComicScrip commented on src/pages/MatchRoom.js
> +    if (this.state.index < this.state.list.length - 1) {
Possibilité de simplifier le if/else ici aussi

2020-04-24 06:36 UTC, ComicScrip commented on src/styles/Button.css
> +/*.session-button-container .session-button.validate {
Code mort

2020-04-27 08:39 UTC, AmelieChevalier commented
@ComicScrip on a cleané l'us7 avec tes remarques.

2020-04-27 19:22 UTC, ComicScrip approved these changes

2020-04-27 19:22 UTC, ComicScrip commented on src/components/FilmCard.js
> +    );
Bien mieux qu'avant :+1: 

On aurait encore pu factoriser tout ça pour facilement étendre à n posters et simplifier la maintenance. MAIS c'est complètement en dehors du périmètre du projet, DONC c'est plutôt justifié. Pour cette fois ;-)

2020-04-27 19:23 UTC, merged