Feature/us14
WildCodeSchool/lyon-js-03-20-p2-g4 pull request #42
Opened 2020-04-28 10:12 UTC by AmelieChevalier

To be reviewed by @tmicka23

2020-04-28 14:12 UTC, tmicka23 commented
ok pour moi !

2020-04-28 15:23 UTC, ComicScrip requested changes

2020-04-28 15:23 UTC, ComicScrip commented on src/pages/MatchRoom.js
> +    this.setState({ index: this.state.index - 1 });
Attention, votre code fonctionne probalement, mais pas de façon déterministe. N'oubliez pas que setState est asynchrone ;) 
Il vaudrait mieux sauvegarder l'index précédent avant d'y faire référence dans le code qui vient après (le setState et la condition)

2020-04-28 15:55 UTC, AmelieChevalier commented on src/pages/MatchRoom.js
> +    this.setState({ index: this.state.index - 1 });
Ok, je pense qu'on a compris ce que tu voulais dire, on a fait le changement, je te laisse vérifier que c'est ok.

2020-05-03 11:23 UTC, ComicScrip commented on src/pages/MatchRoom.js
> +    this.setState({ index: this.state.index - 1 });
:+1:

2020-05-03 11:23 UTC, ComicScrip commented
OK pour moi, reste juste à merge dev ;)

2020-05-04 16:59 UTC, ComicScrip commented
Encore un petit merge svp :p

2020-05-04 18:14 UTC, AmelieChevalier commented
Dev est mergé dedans, ça marche, c'est beau !

2020-05-05 11:17 UTC, ComicScrip approved these changes

2020-05-05 11:17 UTC, merged