Feature/us18
WildCodeSchool/lyon-js-03-20-p2-g4 pull request #46
Opened 2020-05-05 14:05 UTC by Rincevent42

To be reviewed by Amélie

2020-05-05 14:12 UTC, AmelieChevalier commented
Ok pour moi.

2020-05-05 15:20 UTC, ComicScrip requested changes

2020-05-05 15:20 UTC, ComicScrip commented on src/App.js
> +                <MatchRoom {...this.state} {...routeProps} getMatchList={this.getMatchList} getAllPagesNumber={this.getAllPagesNumber} />
prop non-utilisée

2020-05-05 15:20 UTC, ComicScrip commented on src/pages/MatchRoom.js
> +    const numberofPages = 20;
on est pas sûr qu'il y aura 20 pages en tout. Vous pouvez récupérer cette info en faisant une première requete, elle vous renverra un objet avec une clé "total_pages" :)

2020-05-05 17:01 UTC, AmelieChevalier commented on src/App.js
> +                <MatchRoom {...this.state} {...routeProps} getMatchList={this.getMatchList} getAllPagesNumber={this.getAllPagesNumber} />
bien vu elle nous a échappé !

2020-05-05 17:03 UTC, AmelieChevalier commented on src/pages/MatchRoom.js
> +    const numberofPages = 20;
On a rajouté une première requête en effet pour vérifier que le nombre de page était au moins de 20, pour piocher parmi les 20 premières, s'il y en a moins on pioche parmi le nombre total.

2020-05-05 17:03 UTC, AmelieChevalier commented
Corrections faites !

2020-05-06 09:55 UTC, ComicScrip approved these changes

2020-05-06 09:55 UTC, merged