Feature/us15
WildCodeSchool/lyon-js-03-20-p2-g4 pull request #47
Opened 2020-05-05 14:57 UTC by Gottfrieden

2020-05-05 15:14 UTC, AmelieChevalier commented
quelques remarques : 
- un console log dans MatchRoom
- le soulignement en bleu au passage sur les liens "Bande Annonce" et "Plus d'informations"
- ajouter nom des gens dans le casting
- après scroll dans un drawer et ouverture d'un autre, même niveau de scroll

2020-05-05 17:05 UTC, AmelieChevalier commented
C'est bon pour moi.

2020-05-06 10:15 UTC, ComicScrip requested changes

2020-05-06 10:15 UTC, ComicScrip commented on src/components/Drawer.js
> +      .then(data => data.results[0]);
Que se passe-t-il s'il n'y a pas de vidéo pour un film donné ?

2020-05-06 11:41 UTC, AmelieChevalier commented on src/components/Drawer.js
> +      .then(data => data.results[0]);
Comme on utilise fetch ici, s'il n'y a pas de vidéo la fonction nous retourne un objet vide, sans erreur. Ensuite le cas où il n'y a pas de vidéo est géré au moment de l'affichage, si l'objet est vide, le bouton affiche "voir plus d'information" et renvoie vers une recherche google avec le titre du film. Est-ce que c'est bon pour toi comme ça ? Tu peux tester dans la liste Action, le film Coma n'a pas de vidéo par exemple, tu peux aller voir son affichage en cas de match en fin de session.

2020-05-06 12:36 UTC, AmelieChevalier commented
dev est mergé dedans.

2020-05-06 19:20 UTC, ComicScrip approved these changes

2020-05-06 19:20 UTC, merged

2020-05-06 20:01 UTC, tmicka23 commented
@ComicScrip , j'ai re-push cette branche après avoir mergé dev car le Drawer n'apparaissait pas (c'est Fix), sur la version en ligne, malgré le merge dans dev ... (la branche dev et la branche master sont déployées ...)